name: deepvac
channels:
  - defaults
dependencies:
  - python=3.10.19
  - pip
  - pip:
      - -r requirements/training.lock.txt
      - -r requirements/visualization.lock.txt
      - -r requirements/dev.lock.txt
      - -r requirements/package.lock.txt
      - -e .[all]
