services:
  web:
    volumes:
      - ./deepvac/app:/app/app
      - ../optimization:/data/optimization:ro
      - ../gru:/data/gru:ro
    expose:
      - "5000"
    environment:
      - TZ=America/Mexico_City
      - DEEPVAC_DATA_ROOT=/data/optimization
      - DEEPVAC_GRU_ROOT=/data/gru
    command: flask --app wsgi run --host=0.0.0.0 --reload

  fastapi:
    volumes:
      - ./fastapi:/app
    environment:
      - ENV=development
    expose:
      - "8000"

  nginx:
    ports:
      - "80:80"
    volumes:
      - ./nginx/proxy_params:/etc/nginx/proxy_params:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
